name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true
      - name: Generate data
        run: ./gradlew runData
        env:
          APPMEK_VERSION: ${{ github.event.release.tag_name }}
      - name: Build
        run: ./gradlew build
        env:
          APPMEK_VERSION: ${{ github.event.release.tag_name }}
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/Applied-Mekanistics-${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
      - name: Upload to external sites
        run: ./gradlew curseforge modrinth
        env:
          APPMEK_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE: ${{ secrets.CURSEFORGE }}
          MODRINTH: ${{ secrets.MODRINTH }}
